name: pnRtp
version: '${version}'
main: ru.privatenull.pnrtpPlugin
api-version: '1.21'
author: privatenull
commands:
  rtp:
    description: Случайная телепортация
    usage: /rtp
permissions:
  pnrtp.near:
    description: Доступ к /rtp near
    default: false
  pnrtp.default:
    description: Доступ к /rtp default
    default: true
  pnrtp.far:
    description: Доступ к /rtp far
    default: false
  pnrtp.bypass:
    description: Обход кулдауна
    default: op
  pnrtp.admin:
    description: Админ команды (reload, resetcd)
    default: op